export enum ClaimStatus {
  DRAFT = "DRAFT",

  PREAUTH_PENDING = "PREAUTH_PENDING",
  PREAUTH_APPROVED = "PREAUTH_APPROVED",
  PREAUTH_REJECTED = "PREAUTH_REJECTED",

  QUERY_RAISED = "QUERY_RAISED",
  QUERY_RESPONDED = "QUERY_RESPONDED",

  FINAL_BILL_PENDING = "FINAL_BILL_PENDING",

  SETTLEMENT_PENDING = "SETTLEMENT_PENDING",

  PAYMENT_RECEIVED = "PAYMENT_RECEIVED",

  CLOSED = "CLOSED"
}