export enum ClaimStatus {
  DRAFT = "DRAFT",

  PREAUTH_PENDING = "PREAUTH_PENDING",
  PREAUTH_APPROVED = "PREAUTH_APPROVED",
  PREAUTH_REJECTED = "PREAUTH_REJECTED",
  RECONSIDERATION_PENDING = "RECONSIDERATION_PENDING",
  FINAL_APPROVAL_PENDING = "FINAL_APPROVAL_PENDING",
  FINAL_APPROVED = "FINAL_APPROVED",
  FINAL_REJECTED = "FINAL_REJECTED",

  DOCUMENTS_PENDING = "DOCUMENTS_PENDING",
  SUBMITTED = "SUBMITTED",
  QUERY_RAISED = "QUERY_RAISED",
  QUERY_RESPONDED = "QUERY_RESPONSED",

  SETTLEMENT_PENDING = "SETTLEMENT_PENDING",
  SETTLED = "SETTLED",
  DEPOSIT_PENDING = "DEPOSIT_PENDING",
  DEPOSIT_RETURNED = "DEPOSIT_RETURNED",

  CLOSED = "CLOSED",
}
