export enum AuditModule {
  CLAIMS = "CLAIMS",
  SETTLEMENTS = "SETTLEMENTS",
  DEPOSITS = "DEPOSITS",
  DEPARTMENT_ALLOCATIONS = "DEPARTMENT_ALLOCATIONS",
  ALERTS = "ALERTS",
  USERS = "USERS",
  AUTH = "AUTH",
}
