export enum DocumentType {
  PREAUTH = "PREAUTH",
  FINAL_BILL = "FINAL_BILL",
  DISCHARGE_SUMMARY = "DISCHARGE_SUMMARY",
  SETTLEMENT_COPY = "SETTLEMENT_COPY",
  QUERY_DOCUMENT = "QUERY_DOCUMENT",
  LAB_REPORT = "LAB_REPORT",
  PHARMACY_BILL = "PHARMACY_BILL",
  OTHER = "OTHER",
}
