export enum AlertType {
  COURIER_DELAY = "COURIER_DELAY",
  DEPOSIT_MISMATCH = "DEPOSIT_MISMATCH",
  PREAUTH_PENDING = "PREAUTH_PENDING",
  FINAL_APPROVAL_PENDING = "FINAL_APPROVAL_PENDING",
  SETTLEMENT_PENDING = "SETTLEMENT_PENDING",
}
